def opening() :
	print(' _______  __   __  _______  _______  _______    _______  _______  _______  _______  ______   ')   
	print('|       ||  | |  ||       ||   _   ||       |  |  _    ||       ||       ||   _   ||    _ |  ')   
	print('|_     _||  | |  ||    ___||  |_|  ||  _____|  | |_|   ||    ___||  _____||  |_|  ||   | ||  ')  
	print('  |   |  |  |_|  ||   | __ |       || |_____   |       ||   |___ | |_____ |       ||   |_||_ ')   
	print('  |   |  |       ||   ||  ||       ||_____  |  |  _   | |    ___||_____  ||       ||    __  |')   
	print('  |   |  |       ||   |_| ||   _   | _____| |  | |_|   ||   |___  _____| ||   _   ||   |  | |')   
	print('  |___|  |_______||_______||__| |__||_______|  |_______||_______||_______||__| |__||___|  |_|')   
	print('')
	print('                       _______  ___      _______  _______  _______ ')
	print('                      |   _   ||   |    |       ||       ||       |')
	print('                      |  |_|  ||   |    |    ___||    ___||   _   |')
	print('                      |       ||   |    |   | __ |   |___ |  | |  |')
	print('                      |       ||   |___ |   ||  ||    ___||  |_|  |')
	print('                      |   _   ||       ||   |_| ||   |___ |       |')
	print('                      |__| |__||_______||_______||_______||_______|')
	print('')
	print('by Wildan Dicky Alnatara (13516012) dan Dion Saputra (13516045)')
	print('')
	

def menu() :
	print('')
	print('LIST PERINTAH YANG DIGUNAKAN : ')
	print('1.  translate <dx> <dy>')
	print('2.  dilate <k>')
	print('3.  rotate <deg> <a> <b>')
	print('4.  reflect x')
	print('5.  reflect y')
	print('6.  reflect y=x')
	print('7.  reflect y=-x')
	print('8.  reflect (a,b)')
	print('9.  shear x <k>')
	print('10. shear y <k>')
	print('11. stretch x <k>')
	print('12. stretch y <k>')
	print('13. custom <a> <b> <c> <d>')
	print('14. multiple <n>')
	print('15. reset')
	print('16. exit')
	print('')
	
